service: codepipeline-github-status

plugins:
  - serverless-scriptable-plugin
  - serverless-plugin-datadog
  - serverless-plugin-resource-tagging

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: npm run build
  datadog:
    apiKey: ${ssm:/accounts-${opt:stage, self:provider.stage}/datadog_api_key}

package:
  individually: true
  exclude:
    - node_modules/aws-sdk/**

provider:
  name: aws
  memorySize: 128
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'ssm:GetParametersByPath'
      Resource:
        - 'arn:aws:ssm:${self:provider.region}:*:parameter/codepipeline-github-status'
    - Effect: Allow
      Action:
        - 'kms:Decrypt'
      Resource:
        - 'arn:aws:kms:${self:provider.region}:*:key/*'
    - Effect: Allow
      Action:
        - 'codepipeline:GetPipelineExecution'
      Resource:
        - arn:aws:codepipeline:${self:provider.region}:*:*
  stackTags:
    environment: ${opt:stage, self:provider.stage}
    repository: "https://github.com/fishbrain/codepipeline-github-status"
    FibEnvironment: ${opt:stage, self:provider.stage}
    FibOwner: "platform-team"
    FibService: "codepipeline-github-status"

functions:
  main:
    handler: dist/index.handler
    reservedConcurrency: 1
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.codepipeline'
            detail-type:
              - 'CodePipeline Pipeline Execution State Change'
